# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Expert.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Expert.proto',
  package='Interfaces',
  syntax='proto2',
  serialized_pb=b'\n\x0c\x45xpert.proto\x12\nInterfaces\"\xe8\x03\n\rExpertMessage\x12,\n\x04type\x18\x01 \x02(\x0e\x32\x1e.Interfaces.ExpertMessage.Type\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rvariableNames\x18\x03 \x03(\t\x12\x11\n\tvariables\x18\x04 \x03(\x01\x12\x38\n\nestimation\x18\x05 \x01(\x0b\x32$.Interfaces.ExpertMessage.Estimation\x12:\n\x0binformation\x18\x06 \x01(\x0b\x32%.Interfaces.ExpertMessage.Information\x1a-\n\nEstimation\x12\x0c\n\x04mood\x18\x01 \x02(\x01\x12\x11\n\tcertainty\x18\x02 \x02(\x01\x1a\x38\n\x0bInformation\x12\x13\n\x0bisExecutive\x18\x01 \x02(\x08\x12\x14\n\x0cnoPrediction\x18\x02 \x02(\x08\"\x91\x01\n\x04Type\x12\x0b\n\x07getName\x10\x00\x12\x11\n\rgetPrediction\x10\x01\x12\x18\n\x14getRequiredVariables\x10\x02\x12\x0c\n\x08shutdown\x10\x03\x12\t\n\x05reset\x10\x04\x12\x10\n\x0cinformations\x10\x05\x12\x18\n\x14getProvidedVariables\x10\x06\x12\n\n\x06update\x10\x07'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_EXPERTMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Interfaces.ExpertMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='getName', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='getPrediction', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='getRequiredVariables', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='shutdown', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='reset', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='informations', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='getProvidedVariables', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='update', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=372,
  serialized_end=517,
)
_sym_db.RegisterEnumDescriptor(_EXPERTMESSAGE_TYPE)


_EXPERTMESSAGE_ESTIMATION = _descriptor.Descriptor(
  name='Estimation',
  full_name='Interfaces.ExpertMessage.Estimation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mood', full_name='Interfaces.ExpertMessage.Estimation.mood', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='certainty', full_name='Interfaces.ExpertMessage.Estimation.certainty', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=311,
)

_EXPERTMESSAGE_INFORMATION = _descriptor.Descriptor(
  name='Information',
  full_name='Interfaces.ExpertMessage.Information',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isExecutive', full_name='Interfaces.ExpertMessage.Information.isExecutive', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='noPrediction', full_name='Interfaces.ExpertMessage.Information.noPrediction', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=369,
)

_EXPERTMESSAGE = _descriptor.Descriptor(
  name='ExpertMessage',
  full_name='Interfaces.ExpertMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Interfaces.ExpertMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Interfaces.ExpertMessage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variableNames', full_name='Interfaces.ExpertMessage.variableNames', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variables', full_name='Interfaces.ExpertMessage.variables', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='estimation', full_name='Interfaces.ExpertMessage.estimation', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='information', full_name='Interfaces.ExpertMessage.information', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EXPERTMESSAGE_ESTIMATION, _EXPERTMESSAGE_INFORMATION, ],
  enum_types=[
    _EXPERTMESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=517,
)

_EXPERTMESSAGE_ESTIMATION.containing_type = _EXPERTMESSAGE
_EXPERTMESSAGE_INFORMATION.containing_type = _EXPERTMESSAGE
_EXPERTMESSAGE.fields_by_name['type'].enum_type = _EXPERTMESSAGE_TYPE
_EXPERTMESSAGE.fields_by_name['estimation'].message_type = _EXPERTMESSAGE_ESTIMATION
_EXPERTMESSAGE.fields_by_name['information'].message_type = _EXPERTMESSAGE_INFORMATION
_EXPERTMESSAGE_TYPE.containing_type = _EXPERTMESSAGE
DESCRIPTOR.message_types_by_name['ExpertMessage'] = _EXPERTMESSAGE

ExpertMessage = _reflection.GeneratedProtocolMessageType('ExpertMessage', (_message.Message,), dict(

  Estimation = _reflection.GeneratedProtocolMessageType('Estimation', (_message.Message,), dict(
    DESCRIPTOR = _EXPERTMESSAGE_ESTIMATION,
    __module__ = 'Expert_pb2'
    # @@protoc_insertion_point(class_scope:Interfaces.ExpertMessage.Estimation)
    ))
  ,

  Information = _reflection.GeneratedProtocolMessageType('Information', (_message.Message,), dict(
    DESCRIPTOR = _EXPERTMESSAGE_INFORMATION,
    __module__ = 'Expert_pb2'
    # @@protoc_insertion_point(class_scope:Interfaces.ExpertMessage.Information)
    ))
  ,
  DESCRIPTOR = _EXPERTMESSAGE,
  __module__ = 'Expert_pb2'
  # @@protoc_insertion_point(class_scope:Interfaces.ExpertMessage)
  ))
_sym_db.RegisterMessage(ExpertMessage)
_sym_db.RegisterMessage(ExpertMessage.Estimation)
_sym_db.RegisterMessage(ExpertMessage.Information)


# @@protoc_insertion_point(module_scope)
